"""add sku test

Revision ID: 24805cf254f8
Revises: cea86ba69fac
Create Date: 2026-01-15 16:28:30.619200

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24805cf254f8'
down_revision: Union[str, None] = 'cea86ba69fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('tags', sa.Column('sku', sa.String(length=24), nullable=False))
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('tags', 'sku')
	# ### end Alembic commands ###
