"""remove sku

Revision ID: 5886c70609dc
Revises: 24805cf254f8
Create Date: 2026-01-15 16:28:57.900589

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5886c70609dc'
down_revision: Union[str, None] = '24805cf254f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('tags', 'sku')
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('tags', sa.Column('sku', mysql.VARCHAR(length=24), nullable=False))
	# ### end Alembic commands ###
