"""Initial migration

Revision ID: cea86ba69fac
Revises:
Create Date: 2026-01-15 16:27:04.594824

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = 'cea86ba69fac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	pass
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	pass
	# ### end Alembic commands ###
